import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const findRepoRoot = (startDir) => {
  let currentDir = startDir;

  while (true) {
    if (existsSync(path.join(currentDir, "package.json"))) {
      return currentDir;
    }

    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) {
      break;
    }

    currentDir = parentDir;
  }

  throw new Error("Could not locate package.json to resolve repo root.");
};

const repoRoot = findRepoRoot(__dirname);
const puckSourcePath = path.join(repoRoot, "node_modules", "@puckeditor", "core", "dist", "index.css");
const quillSourcePath = path.join(repoRoot, "node_modules", "quill", "dist", "quill.snow.css");
const richTextTablePath = path.resolve(__dirname, "..", "src", "richtext-table.css");
const combinedTargetPath = path.resolve(__dirname, "..", "src", "hoc-website-creation-kit.css");

const stripExternalImports = (css) => {
  return css
    .split("\n")
    .filter((line) => !line.trim().startsWith('@import "https://'))
    .join("\n")
    .trimEnd()
    .concat("\n");
};

const buildCombinedCss = ({ puckCss, quillCss, tableCss }) => {
  const header = "/* Generated by scripts/build-css.mjs. Do not edit manually. */\n";
  return [header, puckCss.trimEnd(), "", quillCss.trimEnd(), "", tableCss.trimEnd(), ""].join("\n");
};

const sync = async () => {
  const puckCssRaw = await readFile(puckSourcePath, "utf8");
  const puckCss = stripExternalImports(puckCssRaw);
  const quillCss = await readFile(quillSourcePath, "utf8");
  const tableCss = await readFile(richTextTablePath, "utf8");

  await writeFile(combinedTargetPath, buildCombinedCss({ puckCss, quillCss, tableCss }), "utf8");

  console.log("Built combined CSS at", combinedTargetPath);
};

sync().catch((error) => {
  console.error("Failed to sync Puck CSS:", error);
  process.exitCode = 1;
});
